#!/usr/bin/env python3
"""Generate the R7 dashboard HTML from a replay/gate result JSON.

Self-contained output: inline CSS, no JS, no external assets. Reads one JSON
file, writes one HTML file. Regenerate after any gate run; never hand-edit.
# ponytail: single-file static render; add live db queries when OSD embeds it.
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path


BANNER = "SYNTHETIC DEMO ONLY — NOT FOR PHYSICAL EXECUTION — NO METHOD CLAIMS"

_STYLES = """
  body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 0;
         background: #f6f7f9; color: #1a1d21; }
  .banner { background: #b45309; color: #fff; text-align: center;
            font-weight: 600; padding: 8px 16px; letter-spacing: .04em; }
  header { background: #fff; border-bottom: 1px solid #e2e5e9; padding: 20px 32px; }
  h1 { margin: 0 0 4px; font-size: 22px; }
  .meta { color: #5c6470; font-size: 13px; }
  main { max-width: 880px; margin: 24px auto; padding: 0 24px; }
  .conclusion { display: inline-block; background: #dcfce7; color: #166534;
                border-radius: 6px; padding: 6px 14px; font-weight: 700; }
  table { width: 100%%; border-collapse: collapse; background: #fff;
          border: 1px solid #e2e5e9; border-radius: 8px; overflow: hidden; }
  th { background: #f0f2f5; text-align: left; font-size: 12px;
       text-transform: uppercase; letter-spacing: .05em; color: #5c6470; }
  th, td { padding: 10px 14px; border-bottom: 1px solid #eceef1; }
  tr:last-child td { border-bottom: none; }
  .pass { color: #166534; font-weight: 600; }
  .hold { color: #b45309; font-weight: 600; }
  .gates { display: flex; gap: 12px; flex-wrap: wrap; margin: 18px 0; }
  .gate { flex: 1; min-width: 150px; background: #fff; border: 1px solid #e2e5e9;
          border-radius: 8px; padding: 12px 14px; }
  .gate b { display: block; font-size: 13px; margin-bottom: 4px; }
  .gate span { color: #5c6470; font-size: 12px; }
  footer { text-align: center; color: #8a919c; font-size: 12px; padding: 24px; }
"""


def esc(value: object) -> str:
    return html.escape(str(value))


def status_class(status: str) -> str:
    return "hold" if ("HOLD" in status or "EXPECTED" in status) else "pass"


def build_html(result: dict, gates_hold: list[str]) -> str:
    chain_rows = "\n".join(
        f'<tr><td>{s["step"]}</td><td><code>{esc(s["skill"])}</code></td>'
        f'<td class="{status_class(s["status"])}">{esc(s["status"])}</td>'
        f"<td>{esc(s.get('stage') or '—')}</td></tr>"
        for s in result["chain"]
    )
    gate_cards = "\n".join(
        f'<div class="gate"><b>{esc(g)}</b><span>HOLD</span></div>' for g in gates_hold
    )
    gaps = "\n".join(f"<li>{esc(g)}</li>" for g in result.get("gaps", []))
    return f"""<!doctype html>
<html lang="zh">
<head>
<meta charset="utf-8">
<title>Lubricant R&D OS — Dashboard</title>
<style>{_STYLES}</style>
</head>
<body>
<div class="banner">{BANNER}</div>
<header>
  <h1>润滑油研发 OS — 项目仪表盘</h1>
  <div class="meta">{esc(result["gate"])} · {esc(result["date"])} · scope: {esc(result["scope"])}</div>
</header>
<main>
  <p>结论 <span class="conclusion">{esc(result["conclusion"])}</span></p>
  <h2 style="font-size:15px">执行链路</h2>
  <table>
    <tr><th>#</th><th>Skill</th><th>状态</th><th>Stage</th></tr>
{chain_rows}
  </table>
  <div class="gates">
{gate_cards}
  </div>
  <h2 style="font-size:15px">已知边界</h2>
  <ul>{gaps}</ul>
</main>
<footer>Generated by lubricant-rd-domain-pack · data is synthetic workflow evidence only</footer>
</body>
</html>"""


def main() -> None:
    result_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    gates_hold = ["Physical Stage A", "Stage A2 / S1b / S2", "G6 真实数据 Gate", "G7 UI 验收"]
    result = json.loads(result_path.read_text(encoding="utf-8"))
    if result.get("scope") != "SYNTHETIC_DEMO_ONLY":
        sys.exit("refusing to generate dashboard without SYNTHETIC_DEMO_ONLY scope")
    out_path.write_text(build_html(result, gates_hold), encoding="utf-8")
    print(f"dashboard written: {out_path}")


if __name__ == "__main__":
    main()
